/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yqqtp.laoyouqian.jctp;

public class CThostFtdcQryTradeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcQryTradeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQryTradeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiv6v3v11JNI.delete_CThostFtdcQryTradeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_ExchangeID_get(swigCPtr, this);
  }

  public void setTradeID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_TradeID_set(swigCPtr, this, value);
  }

  public String getTradeID() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_TradeID_get(swigCPtr, this);
  }

  public void setTradeTimeStart(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_TradeTimeStart_set(swigCPtr, this, value);
  }

  public String getTradeTimeStart() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_TradeTimeStart_get(swigCPtr, this);
  }

  public void setTradeTimeEnd(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_TradeTimeEnd_set(swigCPtr, this, value);
  }

  public String getTradeTimeEnd() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_TradeTimeEnd_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcQryTradeField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return ctpapiv6v3v11JNI.CThostFtdcQryTradeField_InvestUnitID_get(swigCPtr, this);
  }

  public CThostFtdcQryTradeField() {
    this(ctpapiv6v3v11JNI.new_CThostFtdcQryTradeField(), true);
  }

}
