/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yqqtp.laoyouqian.jctp;

public class CThostFtdcReserveOpenAccountConfirmField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcReserveOpenAccountConfirmField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcReserveOpenAccountConfirmField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiv6v3v11JNI.delete_CThostFtdcReserveOpenAccountConfirmField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeCode(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradeCode_set(swigCPtr, this, value);
  }

  public String getTradeCode() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradeCode_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankBranchID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradeTime_get(swigCPtr, this);
  }

  public void setBankSerial(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankSerial_set(swigCPtr, this, value);
  }

  public String getBankSerial() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankSerial_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TradingDay_get(swigCPtr, this);
  }

  public void setPlateSerial(int value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_PlateSerial_set(swigCPtr, this, value);
  }

  public int getPlateSerial() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_PlateSerial_get(swigCPtr, this);
  }

  public void setLastFragment(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_LastFragment_set(swigCPtr, this, value);
  }

  public char getLastFragment() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_LastFragment_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_SessionID_get(swigCPtr, this);
  }

  public void setCustomerName(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CustomerName_set(swigCPtr, this, value);
  }

  public String getCustomerName() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CustomerName_get(swigCPtr, this);
  }

  public void setIdCardType(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_IdCardType_set(swigCPtr, this, value);
  }

  public char getIdCardType() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_IdCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setGender(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Gender_set(swigCPtr, this, value);
  }

  public char getGender() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Gender_get(swigCPtr, this);
  }

  public void setCountryCode(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CountryCode_set(swigCPtr, this, value);
  }

  public String getCountryCode() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CountryCode_get(swigCPtr, this);
  }

  public void setCustType(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CustType_set(swigCPtr, this, value);
  }

  public char getCustType() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CustType_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_ZipCode_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Telephone_get(swigCPtr, this);
  }

  public void setMobilePhone(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_MobilePhone_set(swigCPtr, this, value);
  }

  public String getMobilePhone() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_MobilePhone_get(swigCPtr, this);
  }

  public void setFax(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Fax_set(swigCPtr, this, value);
  }

  public String getFax() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Fax_get(swigCPtr, this);
  }

  public void setEMail(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_EMail_set(swigCPtr, this, value);
  }

  public String getEMail() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_EMail_get(swigCPtr, this);
  }

  public void setMoneyAccountStatus(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_MoneyAccountStatus_set(swigCPtr, this, value);
  }

  public char getMoneyAccountStatus() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_MoneyAccountStatus_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankAccount_get(swigCPtr, this);
  }

  public void setBankPassWord(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankPassWord_set(swigCPtr, this, value);
  }

  public String getBankPassWord() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankPassWord_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_InstallID_get(swigCPtr, this);
  }

  public void setVerifyCertNoFlag(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_VerifyCertNoFlag_set(swigCPtr, this, value);
  }

  public char getVerifyCertNoFlag() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_VerifyCertNoFlag_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_CurrencyID_get(swigCPtr, this);
  }

  public void setDigest(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Digest_set(swigCPtr, this, value);
  }

  public String getDigest() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Digest_get(swigCPtr, this);
  }

  public void setBankAccType(char value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankAccType_set(swigCPtr, this, value);
  }

  public char getBankAccType() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankAccType_get(swigCPtr, this);
  }

  public void setBrokerIDByBank(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BrokerIDByBank_set(swigCPtr, this, value);
  }

  public String getBrokerIDByBank() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BrokerIDByBank_get(swigCPtr, this);
  }

  public void setTID(int value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_TID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_AccountID_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_Password_get(swigCPtr, this);
  }

  public void setBankReserveOpenSeq(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankReserveOpenSeq_set(swigCPtr, this, value);
  }

  public String getBankReserveOpenSeq() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BankReserveOpenSeq_get(swigCPtr, this);
  }

  public void setBookDate(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BookDate_set(swigCPtr, this, value);
  }

  public String getBookDate() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BookDate_get(swigCPtr, this);
  }

  public void setBookPsw(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BookPsw_set(swigCPtr, this, value);
  }

  public String getBookPsw() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_BookPsw_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return ctpapiv6v3v11JNI.CThostFtdcReserveOpenAccountConfirmField_ErrorMsg_get(swigCPtr, this);
  }

  public CThostFtdcReserveOpenAccountConfirmField() {
    this(ctpapiv6v3v11JNI.new_CThostFtdcReserveOpenAccountConfirmField(), true);
  }

}
