/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yqqtp.laoyouqian.jctp;

public class CThostFtdcAccountPropertyField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcAccountPropertyField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcAccountPropertyField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiv6v3v11JNI.delete_CThostFtdcAccountPropertyField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_BrokerID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_AccountID_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_BankID_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_BankAccount_get(swigCPtr, this);
  }

  public void setOpenName(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OpenName_set(swigCPtr, this, value);
  }

  public String getOpenName() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OpenName_get(swigCPtr, this);
  }

  public void setOpenBank(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OpenBank_set(swigCPtr, this, value);
  }

  public String getOpenBank() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OpenBank_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_IsActive_get(swigCPtr, this);
  }

  public void setAccountSourceType(char value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_AccountSourceType_set(swigCPtr, this, value);
  }

  public char getAccountSourceType() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_AccountSourceType_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OpenDate_get(swigCPtr, this);
  }

  public void setCancelDate(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_CancelDate_set(swigCPtr, this, value);
  }

  public String getCancelDate() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_CancelDate_get(swigCPtr, this);
  }

  public void setOperatorID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OperatorID_set(swigCPtr, this, value);
  }

  public String getOperatorID() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OperatorID_get(swigCPtr, this);
  }

  public void setOperateDate(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OperateDate_set(swigCPtr, this, value);
  }

  public String getOperateDate() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OperateDate_get(swigCPtr, this);
  }

  public void setOperateTime(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OperateTime_set(swigCPtr, this, value);
  }

  public String getOperateTime() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_OperateTime_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return ctpapiv6v3v11JNI.CThostFtdcAccountPropertyField_CurrencyID_get(swigCPtr, this);
  }

  public CThostFtdcAccountPropertyField() {
    this(ctpapiv6v3v11JNI.new_CThostFtdcAccountPropertyField(), true);
  }

}
