/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yqqtp.laoyouqian.jctp;

public class CThostFtdcIPListField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcIPListField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcIPListField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiv6v3v11JNI.delete_CThostFtdcIPListField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIPAddress(String value) {
    ctpapiv6v3v11JNI.CThostFtdcIPListField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return ctpapiv6v3v11JNI.CThostFtdcIPListField_IPAddress_get(swigCPtr, this);
  }

  public void setIsWhite(int value) {
    ctpapiv6v3v11JNI.CThostFtdcIPListField_IsWhite_set(swigCPtr, this, value);
  }

  public int getIsWhite() {
    return ctpapiv6v3v11JNI.CThostFtdcIPListField_IsWhite_get(swigCPtr, this);
  }

  public CThostFtdcIPListField() {
    this(ctpapiv6v3v11JNI.new_CThostFtdcIPListField(), true);
  }

}
