/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.yqqtp.laoyouqian.jctp;

public class CThostFtdcFutureLimitPosiParamField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcFutureLimitPosiParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcFutureLimitPosiParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiv6v3v11JNI.delete_CThostFtdcFutureLimitPosiParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorRange(char value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_InvestorRange_set(swigCPtr, this, value);
  }

  public char getInvestorRange() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_InvestorRange_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_InvestorID_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_ProductID_get(swigCPtr, this);
  }

  public void setSpecOpenVolume(int value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_SpecOpenVolume_set(swigCPtr, this, value);
  }

  public int getSpecOpenVolume() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_SpecOpenVolume_get(swigCPtr, this);
  }

  public void setArbiOpenVolume(int value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_ArbiOpenVolume_set(swigCPtr, this, value);
  }

  public int getArbiOpenVolume() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_ArbiOpenVolume_get(swigCPtr, this);
  }

  public void setOpenVolume(int value) {
    ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_OpenVolume_set(swigCPtr, this, value);
  }

  public int getOpenVolume() {
    return ctpapiv6v3v11JNI.CThostFtdcFutureLimitPosiParamField_OpenVolume_get(swigCPtr, this);
  }

  public CThostFtdcFutureLimitPosiParamField() {
    this(ctpapiv6v3v11JNI.new_CThostFtdcFutureLimitPosiParamField(), true);
  }

}
